import React from 'react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { App } from '../App';
import { ChallengeCreator } from '../components/ChallengeCreator';
import { createChallengeUrl, deriveChallengeNumber, generateChallengeSeed, parseChallengeUrl, removeChallengeParams, validateChallenge } from '../utils/challenge';
import { generateShareText } from '../utils/shareResult';
import { sanitizeGameHistory } from '../utils/profileStorage';

const seed = 'abcdef1234567890';
const challengeUrl = (difficulty = 'medium') => `/?challenge=1&difficulty=${difficulty}&seed=${seed}`;

describe('Phase 19 challenge utilities', () => {
  it('generates a safe seed', () => { expect(generateChallengeSeed()).toMatch(/^[a-f0-9]{24}$/); });
  it('derives the same number for the same seed and difficulty', () => { expect(deriveChallengeNumber(seed, 'medium')).toBe(deriveChallengeNumber(seed, 'medium')); });
  it('allows different seeds to produce different challenge numbers', () => { expect(deriveChallengeNumber(seed, 'medium')).not.toBe(deriveChallengeNumber('1234567890abcdef', 'medium')); });
  it.each([['easy', 20], ['medium', 50], ['hard', 100]])('respects the %s range', (difficulty, max) => { const value = deriveChallengeNumber(seed, difficulty); expect(value).toBeGreaterThanOrEqual(1); expect(value).toBeLessThanOrEqual(max); });
  it('rejects invalid derivation inputs', () => { expect(deriveChallengeNumber('bad', 'medium')).toBeNull(); expect(deriveChallengeNumber(seed, 'timed')).toBeNull(); });
  it('creates a URL containing metadata but not the derived secret', () => { const url = createChallengeUrl({ difficulty: 'medium', seed, baseUrl: 'https://example.test/game' }); expect(url).toContain('challenge=1'); expect(url).toContain('difficulty=medium'); expect(url).toContain(`seed=${seed}`); expect(url).not.toContain(String(deriveChallengeNumber(seed, 'medium'))); });
  it('parses valid URLs', () => { expect(parseChallengeUrl(challengeUrl())).toEqual({ version: '1', difficulty: 'medium', seed }); });
  it.each(['', 'challenge=2&difficulty=medium&seed=' + seed, 'challenge=1&difficulty=unknown&seed=' + seed, 'challenge=1&difficulty=medium&seed=too-long!'])('rejects malformed or unsupported links: %s', (query) => { expect(parseChallengeUrl(`http://localhost/?${query}`)).toBeNull(); });
  it('rejects duplicate parameters', () => { expect(parseChallengeUrl(`http://localhost/?challenge=1&challenge=1&difficulty=medium&seed=${seed}`)).toBeNull(); });
  it('rejects oversized seeds', () => { expect(validateChallenge({ version: '1', difficulty: 'easy', seed: 'a'.repeat(33) })).toBe(false); });
  it('removes only challenge parameters during cleanup', () => { expect(removeChallengeParams(`${challengeUrl()}&view=stats`)).toBe('http://localhost/?view=stats'); });
  it('validates supported difficulties and version', () => { expect(validateChallenge({ version: '1', difficulty: 'easy', seed })).toBe(true); expect(validateChallenge({ version: '2', difficulty: 'easy', seed })).toBe(false); });
  it('keeps legacy history valid', () => { expect(sanitizeGameHistory([{ result: 'WIN', difficulty: 'easy', mode: 'classic', attempts: 1 }])[0].isFriendChallenge).toBe(false); });
  it('preserves friend metadata in normalized history', () => { expect(sanitizeGameHistory([{ result: 'WIN', difficulty: 'easy', mode: 'classic', attempts: 1, isFriendChallenge: true }])[0].isFriendChallenge).toBe(true); });
  it('labels friend challenges in share text without seed or secret', () => { const text = generateShareText({ status: 'WON', difficultyName: 'Medium', gameMode: 'classic', attempts: 4, score: 11, isFriendChallenge: true }); expect(text).toContain('Friend Challenge'); expect(text).not.toContain(seed); expect(text).not.toContain('42'); });
  it('does not expose challenge data for unfinished shares', () => { expect(generateShareText({ status: 'PLAYING', isFriendChallenge: true })).toBe(''); });
});

describe('Phase 19 challenge UI and integration', () => {
  beforeEach(() => { localStorage.clear(); window.history.replaceState({}, '', '/'); });
  afterEach(() => { vi.restoreAllMocks(); window.history.replaceState({}, '', '/'); });

  it('renders Challenge a Friend in the Play experience', () => { render(<App />); expect(screen.getByRole('button', { name: 'Challenge a Friend' })).toBeInTheDocument(); });
  it('creates a difficulty-preserving challenge link', () => { render(<App />); fireEvent.click(screen.getByRole('button', { name: 'Challenge a Friend' })); const input = screen.getByLabelText('Challenge link'); expect(input.value).toContain('difficulty=easy'); expect(parseChallengeUrl(input.value)).toMatchObject({ difficulty: 'easy' }); });
  it('copies Challenge Link with accessible feedback', async () => { const writeText = vi.fn().mockResolvedValue(); vi.spyOn(window, 'navigator', 'get').mockReturnValue({ clipboard: { writeText } }); render(<App />); fireEvent.click(screen.getByRole('button', { name: 'Challenge a Friend' })); fireEvent.click(screen.getByRole('button', { name: 'Copy Challenge Link' })); await waitFor(() => expect(screen.getAllByRole('status').some((node) => node.textContent === 'Copied!')).toBe(true)); expect(writeText).toHaveBeenCalledWith(expect.stringContaining('challenge=1')); });
  it('invokes native Share Challenge when available', async () => { const share = vi.fn().mockResolvedValue(); vi.spyOn(window, 'navigator', 'get').mockReturnValue({ share }); render(<App />); fireEvent.click(screen.getByRole('button', { name: 'Challenge a Friend' })); fireEvent.click(screen.getByRole('button', { name: 'Share Challenge' })); await waitFor(() => expect(share).toHaveBeenCalledWith(expect.objectContaining({ url: expect.stringContaining('challenge=1') }))); });
  it('hides native Share Challenge when unavailable', () => { vi.spyOn(window, 'navigator', 'get').mockReturnValue({}); render(<App />); fireEvent.click(screen.getByRole('button', { name: 'Challenge a Friend' })); expect(screen.queryByRole('button', { name: 'Share Challenge' })).not.toBeInTheDocument(); });
  it('handles cancelled native sharing safely', async () => { vi.spyOn(window, 'navigator', 'get').mockReturnValue({ share: vi.fn().mockRejectedValue(new DOMException('cancel', 'AbortError')) }); render(<App />); fireEvent.click(screen.getByRole('button', { name: 'Challenge a Friend' })); fireEvent.click(screen.getByRole('button', { name: 'Share Challenge' })); await waitFor(() => expect(screen.queryByText(/Could not share/)).not.toBeInTheDocument()); });
  it('handles clipboard failure safely', async () => { vi.spyOn(window, 'navigator', 'get').mockReturnValue({ clipboard: { writeText: vi.fn().mockRejectedValue(new Error('no')) } }); render(<App />); fireEvent.click(screen.getByRole('button', { name: 'Challenge a Friend' })); fireEvent.click(screen.getByRole('button', { name: 'Copy Challenge Link' })); await waitFor(() => expect(screen.getAllByRole('status').some((node) => /Could not copy/.test(node.textContent))).toBe(true)); });
  it('renders and accepts a valid invitation, cleaning the URL', () => { window.history.replaceState({}, '', `/?challenge=1&difficulty=medium&seed=${seed}`); render(<App />); const dialog = screen.getByRole('dialog', { name: 'Friend Challenge' }); expect(dialog).toBeInTheDocument(); expect(dialog).toHaveTextContent('Difficulty: Medium'); fireEvent.click(screen.getByRole('button', { name: 'Accept Challenge' })); expect(window.location.search).toBe(''); expect(screen.queryByRole('dialog', { name: 'Friend Challenge' })).not.toBeInTheDocument(); });
  it('dismisses a valid invitation and cleans the URL', () => { window.history.replaceState({}, '', challengeUrl()); render(<App />); fireEvent.click(screen.getByRole('button', { name: 'Dismiss' })); expect(window.location.search).toBe(''); expect(screen.queryByRole('dialog')).not.toBeInTheDocument(); });
  it('rejects malformed invitations without rendering a modal', () => { window.history.replaceState({}, '', '/?challenge=9&difficulty=medium&seed=nope'); render(<App />); expect(screen.queryByRole('dialog', { name: 'Friend Challenge' })).not.toBeInTheDocument(); expect(screen.getByRole('button', { name: 'Check' })).toBeInTheDocument(); });
  it('keeps the friend challenge difficulty after acceptance', () => { window.history.replaceState({}, '', challengeUrl('hard')); render(<App />); fireEvent.click(screen.getByRole('button', { name: 'Accept Challenge' })); expect(screen.getByText(/Guess a Number between 1 and 100/)).toBeInTheDocument(); });
  it('restart keeps the same deterministic friend challenge', () => { window.history.replaceState({}, '', challengeUrl()); render(<App />); fireEvent.click(screen.getByRole('button', { name: 'Accept Challenge' })); const first = deriveChallengeNumber(seed, 'medium'); const input = screen.getByRole('spinbutton', { name: /guess a number/i }); fireEvent.change(input, { target: { value: String(first) } }); fireEvent.keyDown(input, { key: 'Enter' }); fireEvent.click(screen.getByRole('button', { name: 'New Round' })); expect(screen.getByText(/Guess a Number between 1 and 50/)).toBeInTheDocument(); });
  it('identifies the completed friend challenge in the summary', async () => { window.history.replaceState({}, '', challengeUrl()); render(<App />); fireEvent.click(screen.getByRole('button', { name: 'Accept Challenge' })); const input = screen.getByRole('spinbutton', { name: /guess a number/i }); fireEvent.change(input, { target: { value: String(deriveChallengeNumber(seed, 'medium')) } }); fireEvent.keyDown(input, { key: 'Enter' }); await waitFor(() => expect(screen.getByRole('region', { name: 'Round Summary' })).toHaveTextContent(/Friend Challenge/i)); });
  it('keeps themes, keyboard help, analytics, and PWA controls available', () => { render(<App />); fireEvent.keyDown(window, { key: '5' }); expect(screen.getByRole('region', { name: 'Install Application' })).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: /^Light/ })); fireEvent.keyDown(window, { key: '?' }); expect(screen.getByRole('dialog', { name: /keyboard shortcuts/i })).toBeInTheDocument(); fireEvent.keyDown(window, { key: 'Escape' }); fireEvent.keyDown(window, { key: '2' }); expect(screen.getByText('Advanced Analytics')).toBeInTheDocument(); });
  it('does not show native Share Challenge without the API', () => { render(<ChallengeCreator difficulty="hard" />); fireEvent.click(screen.getByRole('button', { name: 'Challenge a Friend' })); expect(screen.queryByRole('button', { name: 'Share Challenge' })).not.toBeInTheDocument(); });
});
